### ISSUE TITLE
Ran the BAT file, not sure if I am supposed to have this exception 

### ISSUE THREAD

**Issue by VanillaSpace** [angelsflyinhell/Cyberpunk2077-RPC#1]
![image](https://user-images.githubusercontent.com/26191487/101993528-635a9900-3c89-11eb-876f-0fbe96131a1e.png)

**Comment by crnvl** [comment]
Fixed this with the [newest Release](https://github.com/angelsflyinhell/Cyberpunk2077-RPC/releases/tag/v1.3). Let me know, if this resolved the Issue.

**Comment by VanillaSpace** [comment]
issue is fixed with the newest Release, thank you!
