### ISSUE TITLE
Incorrect Path

### ISSUE THREAD

**Issue by chrisharris333** [angelsflyinhell/Cyberpunk2077-RPC#5]
Using the standalone for windows, when running run.bat, I get the following error message:

Exception in thread "main" java.nio.file.NoSuchFileException: C:\Users\[myusername]\Saved Games\CD Projekt Red\Cyberpunk 2077

However, the path to my current profile is C:\Users\[myusername].[mydomainname]

Might want to check for domain membership and update the path accordingly.

Thanks,
-Chris

**Comment by crnvl** [comment]
I should probably include custom paths, which should fix your issue.
